arcoiris=("azul","verde","rojo","amarillo")
print(arcoiris)
print("---longitud arcoiris---")
print(len(arcoiris))
animales=("pantera",20,"estatura",1.7)
print(animales)
print("elementos de la tupla")
print(animales[2])
rateros=("juan","ana","pedro")
y = list(rateros)
y [0] ="guisho"
x=tuple(y)

print(x)
print("agregando elementos")
Nanimal=("ElMen","chetos","guisho")
y= list(Nanimal)
print(y)
y.append("guisho")
otratuple=tuple(y)
print(otratuple)
print(" ")
print("uso de for en las tuplas")
for elcolor in arcoiris:
    print(elcolor)